version: '3.1'
services:
  devbox:
    image: "healthsamurai/devbox:0.5.0-SNAPSHOT"
    depends_on:
      - devbox-db
    links:
      - "devbox-db:database"
    ports:
      - "8080:8080"
    env_file:
    - .env
    environment:
      PGHOST: database
      PGDATABASE: devbox
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      AIDBOX_CONFIG: /var/config/config.edn
      AIDBOX_PORT: 8080
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
      - ./config:/var/config
  devbox-db:
    image: "aidbox/db:11.4.0.4"
    ports:
      - "5435:5432"
    volumes:
    - "./pgdata:/data"
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       devbox
  app:
    build: ./
    command: ["wait-for-it.sh", "devbox:8080", "--strict", "--timeout=0", "--", "node", "example.js"]
    depends_on:
      - devbox
    links:
      - devbox
    env_file:
      - .env
    ports:
      - "8989:8989"
    volumes:
      - .:/app
      - ../src:/src
      - ../node_modules:/node_modules
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
